import java.lang.reflect.Method
import java.nio.file.Files
import java.util.concurrent.TimeUnit
import java.util.jar.JarEntry
import java.util.jar.JarFile
import java.util.jar.JarOutputStream

plugins() {
	id('net.fabricmc.fabric-loom') version('1.14-SNAPSHOT')
	//id('maven-publish')
}

version = project.mod_version
group   = project.maven_group

base() {
	archivesName = project.archives_base_name
}

sourceSets() {
	main() {
		java() {
			srcDirs = [
			    file("src/common/java"),
				file("src/${minecraft_version}/java")
			]
		}
		resources() {
			srcDirs = [
				file("src/common/resources"),
				file("src/${minecraft_version}/resources")
			]
		}
	}
	generators() {
		java() {
			srcDirs = [ file("src/generators/java") ]
		}
		resources() {
			srcDirs = [ file("src/generators/resources") ]
		}
		compileClasspath = main.compileClasspath
	}
}

repositories() {
	//Add repositories to retrieve artifacts from in here.
	//You should only use this when depending on other mods because
	//Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	//See https://docs.gradle.org/current/userguide/declaring_repositories.html
	//for more information about repositories.

	mavenLocal() //AutoCodec

	maven() {
		name('Modrinth')
		url('https://api.modrinth.com/maven')
		content() {
			includeGroup('maven.modrinth')
		}
	}

	//manifold
	maven() {
		url('https://oss.sonatype.org/content/repositories/snapshots/')
	}

	//loom does this automatically, but does it too late.
	//we need to ensure this gets added as a repository before
	//all the hacks below that make JIJ dependencies work.
	maven() {
		name = 'MavenCentralLWJGL' //loom checks for this name, so it cannot be changed.
		url(ArtifactRepositoryContainer.MAVEN_CENTRAL_URL)
		content() {
			includeGroup('org.lwjgl')
		}
	}
}

static void extractNestedJars(File dependenciesFolder, File toUnpack) {
	ByteArrayOutputStream baos = new ByteArrayOutputStream(toUnpack.length() as int)
	try (
		JarFile jar = new JarFile(toUnpack)
		JarOutputStream zip = new JarOutputStream(baos)
	) {
		Enumeration<JarEntry> entries = jar.entries()
		while (entries.hasMoreElements()) {
			JarEntry entry = entries.nextElement()
			String name = entry.getName()
			//DH includes sources in the API jar.
			//for whatever dumb reason, this gives me an error on compile that says
			//"[...] is a public class, so it should be in a file named [...].java".
			//this issue doesn't happen when the .java files are stripped out of the jar.
			if (!name.endsWith('.java')) {
				zip.putNextEntry(entry)
				jar.getInputStream(entry).transferTo(zip)
			}
			//DH *also* includes fabric API. strip that out too.
			if (name.startsWith('META-INF/jars/') && name.endsWith('.jar') && !name.regionMatches(false, 'META-inf/jars/'.length(), 'fabric-', 0, 'fabric-'.length())) {
				name = name.substring('META-INF/jars/'.length())
				File unpackDir = new File(dependenciesFolder, name.substring(0, name.length() - '.jar'.length()))
				unpackDir.mkdir()
				File unpacked = new File(unpackDir, name)
				try (FileOutputStream out = new FileOutputStream(unpacked)) {
					jar.getInputStream(entry).transferTo(out)
				}
				extractNestedJars(unpackDir, unpacked)
			}
		}
	}
	toUnpack.bytes = baos.toByteArray()
}

void extractDependencies() {
	File jijDependenciesFolder = file('jijDependencies')
	jijDependenciesFolder.deleteDir()
	jijDependenciesFolder.mkdir()
	for (String dependencyType : [ 'implementation', 'runtimeOnly', 'compileOnly' ]) {
		File specificDependenciesFolder = new File(jijDependenciesFolder, dependencyType)
		specificDependenciesFolder.mkdir()
		for (File from : file("dependencies/${ project.minecraft_version }/$dependencyType").listFiles()) {
			String fileName = from.getName()
			File fromRoot = new File(specificDependenciesFolder, fileName.substring(0, fileName.length() - '.jar'.length()))
			fromRoot.mkdir()
			File to = new File(fromRoot, fileName)
			if (!to.exists()) {
				Files.copy(from.toPath(), to.toPath())
				extractNestedJars(fromRoot, to)
			}
		}
	}
}

dependencies() {
	minecraft("com.mojang:minecraft:${ project.minecraft_version }")
	implementation("net.fabricmc:fabric-loader:${ project.loader_version }")
	implementation("net.fabricmc.fabric-api:fabric-api:${ project.fabric_version }")

	testImplementation('org.junit.jupiter:junit-jupiter:5.7.1')
	testRuntimeOnly('org.junit.platform:junit-platform-launcher')

	String AUTO_CODEC_VERSION = '6.0.3'
	implementation("builderb0y:autocodec:$AUTO_CODEC_VERSION") {
		transitive = false //don't include different version of DFU than what minecraft uses.
	}
	include("builderb0y:autocodec:$AUTO_CODEC_VERSION")

	annotationProcessor('systems.manifold:manifold-preprocessor:2025.1.27')

	if (!Boolean.getBoolean('skipJIJExtraction')) {
		extractDependencies()
	}
	implementation(fileTree(new File('jijDependencies/implementation')))
	compileOnly   (fileTree(new File('jijDependencies/compileOnly')))
	runtimeOnly   (fileTree(new File('jijDependencies/runtimeOnly')))
}

compileJava() {
	//-parameters is enabled lower for all java compile tasks, including tests.
	options.compilerArgs.add('-Xplugin:Manifold')
}

processResources() {
	inputs.property('version', project.version)
	filteringCharset('UTF-8')

	filesMatching('fabric.mod.json') {
		expand('version': project.version, 'mc_version': project.minecraft_version)
	}
}

loom() {
	accessWidenerPath = file("src/${project.minecraft_version}/resources/bigglobe.accesswidener")
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach() {
	//ensure that the encoding is set to UTF-8, no matter what the system default is
	//this fixes some edge cases with special characters not displaying correctly
	//see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
	//If Javadoc is generated, this must be specified in that task too.
	it.options.encoding = "UTF-8"
	//-Xplugin:Manifold is enabled higher for compileJava only.
	it.options.compilerArgs.add('-parameters')

	sourceCompatibility = JavaLanguageVersion.of(targetJavaVersion)
	targetCompatibility = JavaLanguageVersion.of(targetJavaVersion)
}

java() {
	def javaVersion = JavaVersion.toVersion(targetJavaVersion)
	if (JavaVersion.current() < javaVersion) {
		toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
	}
	//Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	//if it is present.
	//If you remove this line, sources will not be generated.
	//withSourcesJar()
}

jar() {
	exclude('assets/bigglobe/icon_1440x.png') //big file that isn't even used.
	exclude('assets/bigglobe/icon_256x_pride.gif') //also not used except as my discord server icon.
}

tasks.register('copyToReleases', Copy) {
	dependsOn(jar)
	from("$projectDir/build/libs") {
		include("$project.archives_base_name-${project.version}.jar")
		rename() {
			"$project.archives_base_name-$project.version-MC${minecraft_version}.jar"
		}
	}
	into(file("releases/${project.version.toString().replace('.' as char, '/' as char)}"))
}

runClient() {
	workingDir = file('run')
	jvmArgs('-Dbigglobe.mixinAudit=true')
	doFirst() {
		assert file('run/.voxy').deleteDir()
	}
}

runServer() {
	//can't seem to find any other way to do this...
	Method getInternalRunDir = it.getClass().getDeclaredMethod('getInternalRunDir')
	getInternalRunDir.setAccessible(true)
	getInternalRunDir.invoke(it).set('server')
	workingDir = file('server')
	jvmArgs("-Duser.dir=${file('server').getAbsolutePath()}", '-Dbigglobe.mixinAudit=true')
	doFirst() {
		assert file('server/world').deleteDir()
	}
}

static Process makeProcess(String taskName) {
	ProcessBuilder builder = new ProcessBuilder('./gradlew', taskName, '--no-daemon', '--stacktrace', '-DskipJIJExtraction=true').redirectErrorStream(true)
	builder.environment().put('JAVA_HOME', System.getProperty('java.home'))
	Process process = builder.start()
	System.out.println("${taskName} gradle process started with pid ${process.pid()}")
	new Thread({
		while (process.isAlive()) {
			String line = process.inputReader().readLine()
			if (line != null) {
				System.out.println("${ taskName }: ${ line }")
				//this really shouldn't be necessary, but *for some reason*, it is.
				if (line.endsWith('\u001B[32m[Render thread/INFO]\u001B[m \u001B[36m(Minecraft)\u001B[m \u001B[0mStopping!')) {
					process.waitFor(10L, TimeUnit.SECONDS)
					process.descendants().forEach(ProcessHandle::destroyForcibly)
					process.destroyForcibly()
					break
				}
			}
		}
	})
	.start()
	return process
}

tasks.register('runClientServer') {
	group('fabric')
	doFirst() {
		Process client = makeProcess('runClient')
		Process server = makeProcess('runServer')
		try {
			println("runClient exited with exit code ${ client.waitFor() }")
			server.descendants().forEach(ProcessHandle::destroy)
			server.destroy()
			println("runServer exited with exit code ${ server.waitFor() }")
		}
		finally {
			client.descendants().forEach(ProcessHandle::destroyForcibly)
			client.destroyForcibly()
			server.descendants().forEach(ProcessHandle::destroyForcibly)
			server.destroyForcibly()
		}
	}
}

test() {
	dependsOn(runClientServer)
	useJUnitPlatform()
	doFirst() {
		if (file("releases/${project.version.toString().replace('.' as char, '/' as char)}/$project.archives_base_name-$project.version-MC${minecraft_version}.jar").exists()) {
			throw new IllegalStateException("Release file $project.version-MC$minecraft_version already exists. If you intend to overwrite this file, delete it first. Otherwise, you probably forgot to bump the version.")
		}
	}
}

build() {
	dependsOn(copyToReleases)
}

tasks.register('checkIfMyCodeCompiles') {
	group('build')
	dependsOn('assemble', 'validateAccessWidener')
}

class Version {

	int year, drop, fix

	Version(int year, int drop, int fix) {
		this.year = year
		this.drop = drop
		this.fix = fix
	}

	static String pad(int number) {
		return number < 10 ? "0$number" : number.toString()
	}

	String shorthand() {
		return "${year}${pad(drop)}${pad(fix)}"
	}

	String longhand() {
		return this.fix == 0 ? "${year}.${drop}" : "${year}.${drop}.${fix}"
	}
}

Collection<Map.Entry<String, String>> loadProperties(String fileName) {
	Properties properties = new Properties()
	try (InputStream stream = new FileInputStream(file(fileName))) {
		properties.load(stream)
	}
	return properties.entrySet()
}

Map<String, String> loadVersion(Version version) {
	return (
		new HashMap<String, String>()
		.putAll(loadProperties('gradle_common.properties'))
		.putAll(loadProperties("gradle_${version.longhand()}.properties"))
	)
}

//this is the dumbest thing I've ever done with gradle.
//its sole purpose is to display the current
//version in the gradle window in intellij.
tasks.register("Currently V$project.version for MC $project.minecraft_version") {
	group('versions')
	doFirst() {
		println("Currently V$project.version for MC $project.minecraft_version")
	}
}

for (Version version in [
	new Version(26, 1, 2),
]) {
	Version capturedVersion = version
	tasks.register("Switch to ${capturedVersion.longhand()}", WriteProperties) {
		group('versions')
		destinationFile = file('gradle.properties')
		comment('This file was automatically generated by gradle. Do not touch!')
		properties(loadVersion(capturedVersion))
		doLast() {
			file('build.properties').text = (
"""#This file was automatically generated by gradle. Do not touch!
MC_26_1_0=260100
MC_26_1_1=260101
MC_26_1_2=260102
MC_VERSION=${capturedVersion.shorthand()}"""
			)
		}
	}
}

/*
// configure the maven publication
publishing() {
	publications() {
		mavenJava(MavenPublication) {
			from(components.java)
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories() {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
*/